// Orval emits both a zod schema value (e.g. `export const SetOppProbabilityBody`)
// in api.ts AND a TypeScript type alias with the same name in types/. A naive
// `export * / export type *` re-export collides (TS2308). Re-export api.ts as-is
// (zod schemas + helpers) and re-export every type from types/ EXCEPT the two
// names that collide with zod schemas; consumers who need those static types can
// import them directly from "@workspace/api-zod/dist/generated/types".
export * from "./generated/api";
export type {
  ActionItem,
  ActionsData,
  ActivityData,
  AuthUser,
  AuthUserEnvelope,
  AuthorizationSessionHeaderParameter,
  BeginBrowserLoginParams,
  CcDeclineItem,
  ClearOppProbability200,
  ErrorEnvelope,
  FetchSheet400,
  FetchSheet502,
  FetchSheetParams,
  GetManagerEstimates200,
  GetManagerEstimates400,
  GetManagerEstimatesParams,
  GetUnreviewedOpportunities200,
  HandleBrowserLoginCallbackParams,
  HealthStatus,
  InboundItem,
  LogoutSuccess,
  ManagerEstimateRow,
  MobileTokenExchangeRequest,
  MobileTokenExchangeSuccess,
  Opportunity,
  PhotoMap,
  PhotoMapPhotos,
  PhotoSyncResult,
  PhotoSyncResultFailedItem,
  PipelineData,
  RepActivity,
  RepActivityDailyTalk,
  RepActivityDemosByProduct24h,
  RepActivityDemosByProduct30d,
  RepActivityOppsByProduct24h,
  RepActivityOppsByProduct30d,
  RepPipeline,
  RepPipelineFunnel,
  RepPipelineProductChurnTypeMods,
  RepPipelineProductChurnTypeModsCount,
  RepPipelineProductChurnTypeModsWeighted,
  RepPipelineProductFunnel,
  RepPipelineProductMods,
  RepPipelineProductModsCount,
  RepPipelineProductModsWeighted,
  RepPipelineProductShare,
  SalesConfig,
  SalesConfigOrg,
  SetOppProbability200,
} from "./generated/types";
