// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/forecast-tornado/Wireframe.tsx": () => import("../components/mockups/forecast-tornado/Wireframe.tsx"),
  "./components/mockups/gnr-forecast-redesign/Mockup.tsx": () => import("../components/mockups/gnr-forecast-redesign/Mockup.tsx"),
  "./components/mockups/gnr-quota-redesign/Mockup.tsx": () => import("../components/mockups/gnr-quota-redesign/Mockup.tsx")
};
